
export interface ItemTranslation {
    symbol: string;
    name: string;
    flavor: string;
}

export interface TranslationSet {
    trait_names: TraitNames
    ship_trait_names: ShipTraitNames
    crew_archetypes: CrewArchetype[]
    ship_archetypes: ShipArchetype[]
    collections: CollectionArchetypes[];
  }

  export interface TraitNames {
    [key: string]: string
    artist: string
    athlete: string
    betelgeusian: string
    brutal: string
    caregiver: string
    casual: string
    chef: string
    civilian: string
    clone: string
    communicator: string
    costumed: string
    counselor: string
    crafty: string
    criminal: string
    cultural_figure: string
    desperate: string
    displaced: string
    duelist: string
    emerald_chain: string
    empath: string
    engineered: string
    explorer: string
    gambler: string
    gardener: string
    hero: string
    hunter: string
    innovator: string
    inspiring: string
    interrogator: string
    investigator: string
    jury_rigger: string
    marksman: string
    maverick: string
    merchant: string
    mirror_universe: string
    musician: string
    pilot: string
    primal: string
    prisoner: string
    prodigy: string
    resourceful: string
    romantic: string
    royalty: string
    saboteur: string
    scoundrel: string
    shapeshifter: string
    smuggler: string
    spiritual: string
    survivalist: string
    tactician: string
    telekinetic: string
    telepath: string
    temporal_agent: string
    thief: string
    tribbled: string
    undercover_operative: string
    villain: string
    augment: string
    dominion: string
    federation: string
    imperial_guard: string
    kca: string
    maco: string
    maquis: string
    obsidian_order: string
    qowat_milat: string
    section31: string
    starfleet: string
    tal_shiar: string
    tardigrade: string
    terran_empire: string
    terran_rebellion: string
    zhat_vash: string
    ambassador: string
    astrophysicist: string
    bartender: string
    botanist: string
    constable: string
    courier: string
    cyberneticist: string
    dahar_master: string
    diplomat: string
    doctor: string
    exoarchaeology: string
    exobiology: string
    exomycologist: string
    geneticist: string
    geologist: string
    high_command: string
    kai: string
    linguist: string
    neurologist: string
    nurse: string
    politician: string
    quantum_mechanics: string
    theoretical_engineer: string
    timekeeper: string
    vedek: string
    veteran: string
    warp_theorist: string
    writer: string
    xenoanthropology: string
    aenar: string
    allasomorph: string
    andorian: string
    android: string
    angosian: string
    antedian: string
    archon: string
    argelian: string
    aurelian: string
    automated_unit: string
    bajoran: string
    baku: string
    barzan: string
    baul: string
    benzite: string
    beta_annari: string
    betazoid: string
    borg: string
    breen: string
    brunali: string
    bynar: string
    caitian: string
    cardassian: string
    chameloid: string
    changeling: string
    control: string
    deltan: string
    denobulan: string
    doopler: string
    dosi: string
    douwd: string
    dramen: string
    edosian: string
    efrosian: string
    elaurian: string
    elaysian: string
    excalbian: string
    ferengi: string
    gorn: string
    hirogen: string
    hologram: string
    human: string
    historian: string
    ikaaran: string
    jahsepp: string
    jemhadar: string
    jnaii: string
    kaelon: string
    kalandan: string
    kantare: string
    kataan: string
    kazon: string
    kelpien: string
    klingon: string
    kiley: string
    kobali: string
    kukulkan: string
    kraylor: string
    krenim: string
    kriosian: string
    ktarian: string
    kwejian: string
    kzinti: string
    kyrian: string
    loqueeque: string
    lotian: string
    lurian: string
    m113_creature: string
    malon: string
    mintakan: string
    mugato: string
    mylean: string
    nacene: string
    nakuhl: string
    nasat: string
    nausicaan: string
    neural: string
    ocampa: string
    orion: string
    pakled: string
    pandronian: string
    photonic: string
    presage: string
    probe: string
    prophet: string
    q: string
    rakhari: string
    ramatis_3_native: string
    reman: string
    risian: string
    romulan: string
    rongovian: string
    sarpeidon: string
    saurian: string
    sentient_computer: string
    serilian: string
    serpent: string
    sikarian: string
    silicon_lifeform: string
    sona: string
    species_8472: string
    suliban: string
    syrrannite: string
    talaxian: string
    talosian: string
    tamarian: string
    tandaran: string
    tanugan: string
    taresian: string
    tellarite: string
    terrellian: string
    tholian: string
    tkon: string
    tosk: string
    tribble: string
    trill: string
    vedala: string
    vidiian: string
    vorta: string
    voth: string
    vulcan: string
    wadi: string
    xahean: string
    xindi: string
    yaderan: string
    yridian: string
    zahl: string
    zibelian: string
    advocate: string
    astronomer: string
    boomer: string
    brat: string
    chancellor: string
    cetacean_biologist: string
    cursed: string
    empress: string
    engineer: string
    evolved: string
    fenris_ranger: string
    khanuttu: string
    lord: string
    torchbearer: string
    mimetic_symbiote: string
    multi_dimensional: string
    president: string
    rich: string
    scientist: string
    senator: string
    shepherd: string
    special_envoy: string
    spy: string
    tailor: string
    warrior: string
    zhiantara: string
    beanlike: string
    firefighter: string
    cool: string
    handsome: string
  }

  export interface ShipTraitNames {
    [key: string]: string
    hirogen: string
    borg: string
    federation: string
    ferengi: string
    cardassian: string
    klingon: string
    romulan: string
    terran: string
    maquis: string
    dominion: string
    andorian: string
    orion_syndicate: string
    vulcan: string
    breen: string
    tholian: string
    malon: string
    gorn: string
    xindi: string
    reman: string
    sikarian: string
    warship: string
    cloaking_device: string
    battle_cruiser: string
    freighter: string
    explorer: string
    fighter: string
    scout: string
    transwarp: string
    ruthless: string
    war_veteran: string
    emp: string
    historic: string
    pioneer: string
    spore_drive: string
    hologram: string
    raider: string
  }

  export interface CrewArchetype {
    symbol: string
    name: string
    short_name: string
    flavor: string
    action: {
      name: string
    }
  }

  export interface ShipArchetype {
    symbol: string
    name: string
    flavor: string
    actions: Action[]
  }

  export interface Action {
    symbol: string
    name: string
  }

  export interface CollectionArchetypes {
    id: number;
    name: string;
    description: string;
  }