/* eslint-disable */

var VoyMod = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(VoyMod) {
  VoyMod = VoyMod || {};

var e;e||(e=typeof VoyMod !== 'undefined' ? VoyMod : {});var aa={},n;for(n in e)e.hasOwnProperty(n)&&(aa[n]=e[n]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,q=!1,ca=!1,da=!1;ba="object"===typeof window;q="function"===typeof importScripts;ca="object"===typeof process&&"function"===typeof require&&!ba&&!q;da=!ba&&!ca&&!q;var r="";
if(ca){r=__dirname+"/";var ea,fa;e.read=function(a,b){ea||(ea=undefined);fa||(fa=undefined);a=fa.normalize(a);a=ea.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;});process.on("unhandledRejection",t);e.quit=function(a){process.exit(a)};
e.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||q)q?r=self.location.href:document.currentScript&&
(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.slice(0,r.lastIndexOf("/")+1):r="",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ia=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),u=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ia);for(n in aa)aa.hasOwnProperty(n)&&(e[n]=aa[n]);aa=void 0;function ja(a){var b=x[la>>2];a=b+a+15&-16;if(a<=z)x[la>>2]=a;else if(!ma(a))return 0;return b}
var na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},oa=0;"object"!==typeof WebAssembly&&u("no native wasm support detected");var pa,qa=!1;function assert(a,b){a||t("Assertion failed: "+b)}function ra(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=A(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)x[a>>2]=0;for(b=d+c;a<b;)B[a++>>0]=0;return d}a.subarray||a.slice?C.set(a,d):C.set(new Uint8Array(a),d);return d}
var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function D(a){return a?ta(C,a,void 0):""}
function ua(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function wa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,B,C,xa,ya,x,E,za,Aa;
function Ba(){e.HEAP8=B=new Int8Array(buffer);e.HEAP16=xa=new Int16Array(buffer);e.HEAP32=x=new Int32Array(buffer);e.HEAPU8=C=new Uint8Array(buffer);e.HEAPU16=ya=new Uint16Array(buffer);e.HEAPU32=E=new Uint32Array(buffer);e.HEAPF32=za=new Float32Array(buffer);e.HEAPF64=Aa=new Float64Array(buffer)}var la=32880,z=e.TOTAL_MEMORY||16777216;5242880>z&&u("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+z+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(pa=new WebAssembly.Memory({initial:z/65536}),buffer=pa.buffer):buffer=new ArrayBuffer(z),e.buffer=buffer);Ba();x[la>>2]=5276016;function Ca(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.$;"number"===typeof c?void 0===b.O?e.dynCall_v(c):e.dynCall_vi(c,b.O):c(void 0===b.O?null:b.O)}}}var Da=[],Ea=[],Fa=[],Ga=[],Ha=!1;function Ia(){var a=e.preRun.shift();Da.unshift(a)}
var F=0,Ja=null,Ka=null;e.preloadedImages={};e.preloadedAudios={};function La(){var a=G;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var G="voymod.wasm";if(!La()){var Ma=G;G=e.locateFile?e.locateFile(Ma,r):r+Ma}function Na(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(G);throw"both async and sync fetching of the wasm failed";}catch(a){t(a)}}
function Oa(){return e.wasmBinary||!ba&&!q||"function"!==typeof fetch?new Promise(function(a){a(Na())}):fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Na()})}
function Pa(a){function b(a){e.asm=a.exports;F--;e.monitorRunDependencies&&e.monitorRunDependencies(F);0==F&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka&&(a=Ka,Ka=null,a()))}function c(a){b(a.instance)}function d(a){Oa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){u("failed to asynchronously prepare wasm: "+a);t(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:na};F++;e.monitorRunDependencies&&e.monitorRunDependencies(F);if(e.instantiateWasm)try{return e.instantiateWasm(f,
b)}catch(g){return u("Module.instantiateWasm callback failed with error: "+g),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||La()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(G,{credentials:"same-origin"}),f).then(c,function(a){u("wasm streaming compile failed: "+a);u("falling back to ArrayBuffer instantiation");d(c)});return{}}
e.asm=function(a,b){b.memory=pa;b.table=new WebAssembly.Table({initial:1002,maximum:1002,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Pa(b)};Ea.push({$:function(){Qa()}});var H={};
function Ra(a){if(Ra.R){var b=x[a>>2];var c=x[b>>2]}else Ra.R=!0,H.USER=H.LOGNAME="web_user",H.PATH="/",H.PWD="/",H.HOME="/home/web_user",H.LANG="C.UTF-8",H._=e.thisProgram,c=Ha?A(1024):ja(1024),b=Ha?A(256):ja(256),x[b>>2]=c,x[a>>2]=b;a=[];var d=0,f;for(f in H)if("string"===typeof H[f]){var g=f+"="+H[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,k=0;k<d.length;++k)B[h++>>0]=d.charCodeAt(k);B[h>>0]=0;x[b+4*f>>
2]=c;c+=g.length+1}x[b+4*a.length>>2]=0}function Sa(a){try{return I(a)}catch(b){}}var Ta=0,Va=[],J={};function Wa(a){if(!a||J[a])return a;for(var b in J)for(var c=+b,d=J[c].T,f=d.length,g=0;g<f;g++)if(d[g]===a)return c;return a}
function K(){var a=Ta;if(!a)return oa=0;var b=J[a],c=b.type;if(!c)return oa=0,a|0;var d=Array.prototype.slice.call(arguments);e.___cxa_is_pointer_type(c);K.buffer||(K.buffer=A(4));x[K.buffer>>2]=a;a=K.buffer;for(var f=0;f<d.length;f++)if(d[f]&&e.___cxa_can_catch(d[f],c,a))return a=x[a>>2],b.T.push(a),oa=d[f],a|0;a=x[a>>2];oa=c;return a|0}function Xa(a){e.___errno_location&&(x[e.___errno_location()>>2]=a);return a}var Ya=[null,[],[]];
function Za(a,b){var c=Ya[a];0===b||10===b?((1===a?ia:u)(ta(c,0)),c.length=0):c.push(b)}var L=0;function M(){L+=4;return x[L-4>>2]}var N={};function $a(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}function ab(){for(var a=Array(256),b=0;256>b;++b)a[b]=String.fromCharCode(b);bb=a}var bb=void 0;function O(a){for(var b="";C[a];)b+=bb[C[a++]];return b}var cb={},P={},db={};
function eb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function fb(a,b){a=eb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function gb(a,b){var c=fb(b,function(a){this.name=b;this.message=a;a=Error(a).stack;void 0!==a&&(this.stack=this.toString()+"\n"+a.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var hb=void 0;function Q(a){throw new hb(a);}var ib=void 0;function jb(a){throw new ib(a);}
function R(a,b,c){function d(b){b=c(b);b.length!==a.length&&jb("Mismatched type converter count");for(var d=0;d<a.length;++d)S(a[d],b[d])}a.forEach(function(a){db[a]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(a,b){P.hasOwnProperty(a)?f[b]=P[a]:(g.push(a),cb.hasOwnProperty(a)||(cb[a]=[]),cb[a].push(function(){f[b]=P[a];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.ea)return;Q("Cannot register type '"+d+"' twice")}P[a]=b;delete db[a];cb.hasOwnProperty(a)&&(b=cb[a],delete cb[a],b.forEach(function(a){a()}))}
function kb(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.a.f.b,c=this.a.c,d=a.a.f.b;for(a=a.a.c;b.l;)c=b.G(c),b=b.l;for(;d.l;)a=d.G(a),d=d.l;return b===d&&c===a}function lb(a){return{count:a.count,B:a.B,F:a.F,c:a.c,f:a.f,i:a.i,j:a.j}}function mb(a){Q(a.a.f.b.name+" instance already deleted")}function nb(){this.a.c||mb(this);if(this.a.F)return this.a.count.value+=1,this;var a=Object.create(Object.getPrototypeOf(this),{a:{value:lb(this.a)}});a.a.count.value+=1;a.a.B=!1;return a}
function ob(a){a=a.a;a.i?a.j.w(a.i):a.f.b.w(a.c)}function pb(){this.a.c||mb(this);this.a.B&&!this.a.F&&Q("Object already scheduled for deletion");--this.a.count.value;0===this.a.count.value&&ob(this);this.a.F||(this.a.i=void 0,this.a.c=void 0)}function qb(){return!this.a.c}var rb=void 0,sb=[];function tb(){for(;sb.length;){var a=sb.pop();a.a.B=!1;a["delete"]()}}
function ub(){this.a.c||mb(this);this.a.B&&!this.a.F&&Q("Object already scheduled for deletion");sb.push(this);1===sb.length&&rb&&rb(tb);this.a.B=!0;return this}function vb(){T.prototype.isAliasOf=kb;T.prototype.clone=nb;T.prototype["delete"]=pb;T.prototype.isDeleted=qb;T.prototype.deleteLater=ub}function T(){}var wb={};
function xb(a,b,c){if(void 0===a[b].h){var d=a[b];a[b]=function(){a[b].h.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].h+")!");return a[b].h[arguments.length].apply(this,arguments)};a[b].h=[];a[b].h[d.H]=d}}
function yb(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].h&&void 0!==e[a].h[c])&&Q("Cannot register public name '"+a+"' twice"),xb(e,a,a),e.hasOwnProperty(c)&&Q("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].h[c]=b):(e[a]=b,void 0!==c&&(e[a].ya=c))}function zb(a,b,c,d,f,g,h,k){this.name=a;this.constructor=b;this.C=c;this.w=d;this.l=f;this.aa=g;this.G=h;this.Z=k;this.ia=[]}
function Ab(a,b,c){for(;b!==c;)b.G||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.G(a),b=b.l;return a}function Bb(a,b){if(null===b)return this.S&&Q("null is not a valid "+this.name),0;b.a||Q('Cannot pass "'+Cb(b)+'" as a '+this.name);b.a.c||Q("Cannot pass deleted object as a pointer of type "+this.name);return Ab(b.a.c,b.a.f.b,this.b)}
function Db(a,b){if(null===b){this.S&&Q("null is not a valid "+this.name);if(this.K){var c=this.ja();null!==a&&a.push(this.w,c);return c}return 0}b.a||Q('Cannot pass "'+Cb(b)+'" as a '+this.name);b.a.c||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.J&&b.a.f.J&&Q("Cannot convert argument of type "+(b.a.j?b.a.j.name:b.a.f.name)+" to parameter type "+this.name);c=Ab(b.a.c,b.a.f.b,this.b);if(this.K)switch(void 0===b.a.i&&Q("Passing raw pointer to smart pointer is illegal"),this.la){case 0:b.a.j===
this?c=b.a.i:Q("Cannot convert argument of type "+(b.a.j?b.a.j.name:b.a.f.name)+" to parameter type "+this.name);break;case 1:c=b.a.i;break;case 2:if(b.a.j===this)c=b.a.i;else{var d=b.clone();c=this.ka(c,Eb(function(){d["delete"]()}));null!==a&&a.push(this.w,c)}break;default:Q("Unsupporting sharing policy")}return c}
function Fb(a,b){if(null===b)return this.S&&Q("null is not a valid "+this.name),0;b.a||Q('Cannot pass "'+Cb(b)+'" as a '+this.name);b.a.c||Q("Cannot pass deleted object as a pointer of type "+this.name);b.a.f.J&&Q("Cannot convert argument of type "+b.a.f.name+" to parameter type "+this.name);return Ab(b.a.c,b.a.f.b,this.b)}function Gb(a){return this.fromWireType(E[a>>2])}function Hb(a){this.W&&(a=this.W(a));return a}function Ib(a){this.w&&this.w(a)}function Jb(a){if(null!==a)a["delete"]()}
function Kb(a,b,c){if(b===c)return a;if(void 0===c.l)return null;a=Kb(a,b,c.l);return null===a?null:c.Z(a)}function Lb(){return Object.keys(Mb).length}function Nb(){var a=[],b;for(b in Mb)Mb.hasOwnProperty(b)&&a.push(Mb[b]);return a}function Ob(a){rb=a;sb.length&&rb&&rb(tb)}function Pb(){e.getInheritedInstanceCount=Lb;e.getLiveInheritedInstances=Nb;e.flushPendingDeletes=tb;e.setDelayFunction=Ob}var Mb={};
function Qb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.l;)b=a.G(b),a=a.l;return b}function Rb(a,b){b=Qb(a,b);return Mb[b]}function Sb(a,b){b.f&&b.c||jb("makeClassHandle requires ptr and ptrType");!!b.j!==!!b.i&&jb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Object.create(a,{a:{value:b}})}
function Tb(a){function b(){return this.K?Sb(this.b.C,{f:this.ha,c:c,j:this,i:a}):Sb(this.b.C,{f:this,c:a})}var c=this.ba(a);if(!c)return this.D(a),null;var d=Rb(this.b,c);if(void 0!==d){if(0===d.a.count.value)return d.a.c=c,d.a.i=a,d.clone();d=d.clone();this.D(a);return d}d=this.b.aa(c);d=wb[d];if(!d)return b.call(this);d=this.J?d.Y:d.pointerType;var f=Kb(c,this.b,d.b);return null===f?b.call(this):this.K?Sb(d.b.C,{f:d,c:f,j:this,i:a}):Sb(d.b.C,{f:d,c:f})}
function Ub(){U.prototype.ba=Hb;U.prototype.D=Ib;U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=Gb;U.prototype.deleteObject=Jb;U.prototype.fromWireType=Tb}function U(a,b,c,d,f,g,h,k,m,l,p){this.name=a;this.b=b;this.S=c;this.J=d;this.K=f;this.ha=g;this.la=h;this.W=k;this.ja=m;this.ka=l;this.w=p;f||void 0!==b.l?this.toWireType=Db:(this.toWireType=d?Bb:Fb,this.o=null)}
function Vb(a,b,c){e.hasOwnProperty(a)||jb("Replacing nonexistant public symbol");void 0!==e[a].h&&void 0!==c?e[a].h[c]=b:(e[a]=b,e[a].H=c)}
function V(a,b){a=O(a);if(void 0!==e["FUNCTION_TABLE_"+a])var c=e["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=e["dynCall_"+a];void 0===c&&(c=e["dynCall_"+a.replace(/f/g,"d")],void 0===c&&Q("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Wb=void 0;function Xb(a){a=Yb(a);var b=O(a);I(a);return b}function Zb(a,b){function c(a){f[a]||P[a]||(db[a]?db[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Wb(a+": "+d.map(Xb).join([", "]));}function $b(a,b){for(var c=[],d=0;d<a;d++)c.push(x[(b>>2)+d]);return c}function ac(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function bc(a,b){if(!(a instanceof Function))throw new TypeError("new_ called with constructor type "+typeof a+" which is not a function");var c=fb(a.name||"unknownFunctionName",function(){});c.prototype=a.prototype;c=new c;a=a.apply(c,b);return a instanceof Object?a:c}
function cc(a,b,c,d,f){var g=b.length;2>g&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].o){k=!0;break}var m="void"!==b[0].name,l="",p="";for(c=0;c<g-2;++c)l+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+eb(a)+"("+l+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var v=k?"destructors":"null";l="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,f,ac,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",l.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].o&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",l.push(g+"_dtor"),d.push(b[c].o));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");l.push(a+"}\n");return bc(Function,l).apply(null,d)}var dc=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function ec(a){4<a&&0===--W[a].s&&(W[a]=void 0,dc.push(a))}
function fc(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a}function hc(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null}function ic(){e.count_emval_handles=fc;e.get_first_emval=hc}function Eb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=dc.length?dc.pop():W.length;W[b]={s:1,value:a};return b}}
function Cb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function jc(a,b){switch(b){case 2:return function(a){return this.fromWireType(za[a>>2])};case 3:return function(a){return this.fromWireType(Aa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function kc(a,b,c){switch(b){case 0:return c?function(a){return B[a]}:function(a){return C[a]};case 1:return c?function(a){return xa[a>>1]}:function(a){return ya[a>>1]};case 2:return c?function(a){return x[a>>2]}:function(a){return E[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function lc(a,b){var c=P[a];void 0===c&&Q(b+" has unknown type "+Xb(a));return c}function mc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=lc(x[(b>>2)+d],"parameter "+d);return c}
function nc(a){a||Q("Cannot use deleted val. handle = "+a);return W[a].value}var oc={};function pc(a){var b=oc[a];return void 0===b?O(a):b}var qc=[];function rc(a){var b=qc.length;qc.push(a);return b}function sc(){t()}function tc(){return ca||"undefined"!==typeof dateNow||(ba||q)&&self.performance&&self.performance.now}function uc(a){a=wa(a);var b=e.buffer.byteLength;try{return-1!==pa.grow((a-b)/65536)?e.buffer=pa.buffer:null}catch(c){return null}}
function ma(a){if(2147418112<a)return!1;for(var b=Math.max(z,16777216);b<a;)536870912>=b?b=wa(2*b):b=Math.min(wa((3*b+2147483648)/4),2147418112);var c=uc(b);if(!c||c.byteLength!=b)return!1;e.buffer=buffer=c;Ba();z=b;E[la>>2]=a;return!0}function vc(a){if(0===a)return 0;a=D(a);if(!H.hasOwnProperty(a))return 0;vc.m&&I(vc.m);a=H[a];var b=va(a)+1,c=A(b);c&&ua(a,B,c,b);vc.m=c;return vc.m}function wc(){wc.m||(wc.m=[]);wc.m.push(X());return wc.m.length-1}ua("GMT",C,33024,4);
function xc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!xc.R){xc.R=!0;x[yc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);x[zc()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),f=a(c);d=ra(Ac(d));f=ra(Ac(f));c.getTimezoneOffset()<b.getTimezoneOffset()?(x[Bc()>>2]=d,x[Bc()+4>>2]=f):(x[Bc()>>2]=f,x[Bc()+4>>2]=d)}}
function Cc(a,b){xc();a=new Date(1E3*x[a>>2]);x[b>>2]=a.getSeconds();x[b+4>>2]=a.getMinutes();x[b+8>>2]=a.getHours();x[b+12>>2]=a.getDate();x[b+16>>2]=a.getMonth();x[b+20>>2]=a.getFullYear()-1900;x[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);x[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;x[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;x[b+32>>2]=a;a=x[Bc()+(a?4:0)>>2];x[b+40>>2]=
a;return b}function Dc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ec(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Fc=[31,29,31,30,31,30,31,31,30,31,30,31],Gc=[31,28,31,30,31,30,31,31,30,31,30,31];function Hc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Dc(a.getFullYear())?Fc:Gc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ic(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function k(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function m(a){a=Hc(new Date(a.g+1900,0,1),a.N);var b=k(new Date(a.getFullYear()+1,0,4));return 0>=h(k(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var l=x[d+40>>2];d={oa:x[d>>2],na:x[d+4>>2],M:x[d+8>>2],A:x[d+12>>2],u:x[d+16>>2],g:x[d+20>>2],X:x[d+24>>2],N:x[d+28>>2],za:x[d+32>>2],ma:x[d+36>>2],pa:l?D(l):
""};c=D(c);l={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var p in l)c=c.replace(new RegExp(p,"g"),l[p]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),w="January February March April May June July August September October November December".split(" ");l={"%a":function(a){return v[a.X].substring(0,3)},"%A":function(a){return v[a.X]},"%b":function(a){return w[a.u].substring(0,
3)},"%B":function(a){return w[a.u]},"%C":function(a){return g((a.g+1900)/100|0,2)},"%d":function(a){return g(a.A,2)},"%e":function(a){return f(a.A,2," ")},"%g":function(a){return m(a).toString().substring(2)},"%G":function(a){return m(a)},"%H":function(a){return g(a.M,2)},"%I":function(a){a=a.M;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.A+Ec(Dc(a.g+1900)?Fc:Gc,a.u-1),3)},"%m":function(a){return g(a.u+1,2)},"%M":function(a){return g(a.na,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.M&&12>a.M?"AM":"PM"},"%S":function(a){return g(a.oa,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.g+1900,a.u+1,a.A,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.g+1900,0,1),c=0===b.getDay()?b:Hc(b,7-b.getDay());a=new Date(a.g+1900,a.u,a.A);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ec(Dc(a.getFullYear())?Fc:Gc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=k(new Date(a.g+1900,0,4)),c=k(new Date(a.g+1901,0,4)),d=Hc(new Date(a.g+
1900,0,1),a.N);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.g+1900?a.N+32-b.getDate():a.N+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.g+1900,a.u+1,a.A,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.g,0,1),c=1===b.getDay()?b:Hc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.g+1900,a.u,a.A);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ec(Dc(a.getFullYear())?Fc:Gc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.g+1900).toString().substring(2)},
"%Y":function(a){return a.g+1900},"%z":function(a){a=a.ma;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.pa},"%%":function(){return"%"}};for(p in l)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),l[p](d)));p=Ac(c,!1);if(p.length>b)return 0;B.set(p,a);return p.length-1}ab();hb=e.BindingError=gb(Error,"BindingError");ib=e.InternalError=gb(Error,"InternalError");vb();Ub();Pb();Wb=e.UnboundTypeError=gb(Error,"UnboundTypeError");ic();
ca?sc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?sc=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?sc=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?sc=function(){return performance.now()}:sc=Date.now;function Ac(a,b){var c=Array(va(a)+1);a=ua(a,c,0,c.length);b&&(c.length=a);return c}
var md=e.asm({},{abort:t,setTempRet0:function(a){oa=a},getTempRet0:function(){return oa},invoke_diii:function(a,b,c,d){var f=X();try{return Jc(a,b,c,d)}catch(g){Y(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}},invoke_fiii:function(a,b,c,d){var f=X();try{return Kc(a,b,c,d)}catch(g){Y(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}},invoke_i:function(a){var b=X();try{return Lc(a)}catch(c){Y(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}},invoke_ii:function(a,b){var c=X();try{return Oc(a,b)}catch(d){Y(c);
if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}},invoke_iif:function(a,b,c){var d=X();try{return Pc(a,b,c)}catch(f){Y(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}},invoke_iii:function(a,b,c){var d=X();try{return Qc(a,b,c)}catch(f){Y(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}},invoke_iiii:function(a,b,c,d){var f=X();try{return Rc(a,b,c,d)}catch(g){Y(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}},invoke_iiiii:function(a,b,c,d,f){var g=X();try{return Sc(a,b,c,d,f)}catch(h){Y(g);if(h!==h+0&&"longjmp"!==h)throw h;
Z(1,0)}},invoke_iiiiid:function(a,b,c,d,f,g){var h=X();try{return Tc(a,b,c,d,f,g)}catch(k){Y(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}},invoke_iiiiii:function(a,b,c,d,f,g){var h=X();try{return Uc(a,b,c,d,f,g)}catch(k){Y(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}},invoke_iiiiiii:function(a,b,c,d,f,g,h){var k=X();try{return Vc(a,b,c,d,f,g,h)}catch(m){Y(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}},invoke_iiiiiiii:function(a,b,c,d,f,g,h,k){var m=X();try{return Wc(a,b,c,d,f,g,h,k)}catch(l){Y(m);
if(l!==l+0&&"longjmp"!==l)throw l;Z(1,0)}},invoke_iiiiiiiii:function(a,b,c,d,f,g,h,k,m){var l=X();try{return Xc(a,b,c,d,f,g,h,k,m)}catch(p){Y(l);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}},invoke_iiiiiiiiiii:function(a,b,c,d,f,g,h,k,m,l,p){var v=X();try{return Yc(a,b,c,d,f,g,h,k,m,l,p)}catch(w){Y(v);if(w!==w+0&&"longjmp"!==w)throw w;Z(1,0)}},invoke_iiiiiiiiiiii:function(a,b,c,d,f,g,h,k,m,l,p,v){var w=X();try{return Zc(a,b,c,d,f,g,h,k,m,l,p,v)}catch(y){Y(w);if(y!==y+0&&"longjmp"!==y)throw y;Z(1,0)}},
invoke_iiiiiiiiiiiii:function(a,b,c,d,f,g,h,k,m,l,p,v,w){var y=X();try{return $c(a,b,c,d,f,g,h,k,m,l,p,v,w)}catch(ka){Y(y);if(ka!==ka+0&&"longjmp"!==ka)throw ka;Z(1,0)}},invoke_iiiiij:function(a,b,c,d,f,g,h){var k=X();try{return ad(a,b,c,d,f,g,h)}catch(m){Y(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}},invoke_iij:function(a,b,c,d){var f=X();try{return bd(a,b,c,d)}catch(g){Y(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}},invoke_jiiii:function(a,b,c,d,f){var g=X();try{return cd(a,b,c,d,f)}catch(h){Y(g);
if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}},invoke_v:function(a){var b=X();try{dd(a)}catch(c){Y(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}},invoke_vi:function(a,b){var c=X();try{ed(a,b)}catch(d){Y(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}},invoke_vii:function(a,b,c){var d=X();try{fd(a,b,c)}catch(f){Y(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}},invoke_viii:function(a,b,c,d){var f=X();try{gd(a,b,c,d)}catch(g){Y(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}},invoke_viiii:function(a,b,c,d,f){var g=
X();try{hd(a,b,c,d,f)}catch(h){Y(g);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}},invoke_viiiiiii:function(a,b,c,d,f,g,h,k){var m=X();try{id(a,b,c,d,f,g,h,k)}catch(l){Y(m);if(l!==l+0&&"longjmp"!==l)throw l;Z(1,0)}},invoke_viiiiiiiiii:function(a,b,c,d,f,g,h,k,m,l,p){var v=X();try{jd(a,b,c,d,f,g,h,k,m,l,p)}catch(w){Y(v);if(w!==w+0&&"longjmp"!==w)throw w;Z(1,0)}},invoke_viiiiiiiiiiiiiii:function(a,b,c,d,f,g,h,k,m,l,p,v,w,y,ka,Mc){var Nc=X();try{kd(a,b,c,d,f,g,h,k,m,l,p,v,w,y,ka,Mc)}catch(Ua){Y(Nc);if(Ua!==
Ua+0&&"longjmp"!==Ua)throw Ua;Z(1,0)}},ClassHandle:T,ClassHandle_clone:nb,ClassHandle_delete:pb,ClassHandle_deleteLater:ub,ClassHandle_isAliasOf:kb,ClassHandle_isDeleted:qb,RegisteredClass:zb,RegisteredPointer:U,RegisteredPointer_deleteObject:Jb,RegisteredPointer_destructor:Ib,RegisteredPointer_fromWireType:Tb,RegisteredPointer_getPointee:Hb,___assert_fail:function(a,b,c,d){t("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},___buildEnvironment:Ra,___cxa_allocate_exception:function(a){return A(a)},
___cxa_begin_catch:function(a){var b=J[a];b&&!b.U&&(b.U=!0,ld.P--);b&&(b.L=!1);Va.push(a);(b=Wa(a))&&J[b].s++;return a},___cxa_end_catch:function(){Z(0);var a=Va.pop();if(a){if(a=Wa(a)){var b=J[a];assert(0<b.s);b.s--;0!==b.s||b.L||(b.D&&e.dynCall_vi(b.D,a),delete J[a],Sa(a))}Ta=0}},___cxa_find_matching_catch:K,___cxa_find_matching_catch_2:function(){return K.apply(null,arguments)},___cxa_find_matching_catch_3:function(){return K.apply(null,arguments)},___cxa_free_exception:Sa,___cxa_rethrow:function(){var a=
Va.pop();a=Wa(a);J[a].L||(Va.push(a),J[a].L=!0);Ta=a;throw a;},___cxa_throw:function(a,b,c){J[a]={c:a,T:[a],type:b,D:c,s:0,U:!1,L:!1};Ta=a;"uncaught_exception"in ld?ld.P++:ld.P=1;throw a;},___cxa_uncaught_exception:function(){return!!ld.P},___gxx_personality_v0:function(){},___lock:function(){},___map_file:function(){Xa(1);return-1},___resumeException:function(a){Ta||(Ta=a);throw a;},___setErrNo:Xa,___syscall140:function(a,b){L=b;try{var c=N.V();M();var d=M(),f=M(),g=M();(void 0).va(c,d,g);x[f>>2]=
c.position;c.da&&0===d&&0===g&&(c.da=null);return 0}catch(h){return t(h),-h.I}},___syscall145:function(a,b){L=b;try{var c=N.V(),d=M(),f=M();return N.sa(c,d,f)}catch(g){return t(g),-g.I}},___syscall146:function(a,b){L=b;try{var c=M(),d=M(),f=M();for(b=a=0;b<f;b++){for(var g=x[d+8*b>>2],h=x[d+(8*b+4)>>2],k=0;k<h;k++)Za(c,C[g+k]);a+=h}return a}catch(m){return t(m),-m.I}},___syscall54:function(a,b){L=b;return 0},___syscall6:function(a,b){L=b;try{var c=N.V();(void 0).close(c);return 0}catch(d){return t(d),
-d.I}},___syscall91:function(a,b){L=b;try{var c=M(),d=M(),f=N.ga[c];if(!f)return 0;if(d===f.ua){var g=(void 0).ta(f.fd);N.ra(c,g,d,f.flags);(void 0).xa(g);N.ga[c]=null;f.qa&&I(f.wa)}return 0}catch(h){return t(h),-h.I}},___unlock:function(){},__addDays:Hc,__arraySum:Ec,__embind_register_bool:function(a,b,c,d,f){var g=$a(c);b=O(b);S(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=B;else if(2===c)d=
xa;else if(4===c)d=x;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},o:null})},__embind_register_class:function(a,b,c,d,f,g,h,k,m,l,p,v,w){p=O(p);g=V(f,g);k&&(k=V(h,k));l&&(l=V(m,l));w=V(v,w);var y=eb(p);yb(y,function(){Zb("Cannot construct "+p+" due to unbound types",[d])});R([a,b,c],d?[d]:[],function(b){b=b[0];if(d){var c=b.b;var f=c.C}else f=T.prototype;b=fb(y,function(){if(Object.getPrototypeOf(this)!==h)throw new hb("Use 'new' to construct "+p);if(void 0===
m.v)throw new hb(p+" has no accessible constructor");var a=m.v[arguments.length];if(void 0===a)throw new hb("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(m.v).toString()+") parameters instead!");return a.apply(this,arguments)});var h=Object.create(f,{constructor:{value:b}});b.prototype=h;var m=new zb(p,b,h,w,c,g,k,l);c=new U(p,m,!0,!1,!1);f=new U(p+"*",m,!1,!1,!1);var v=new U(p+" const*",m,!1,!0,!1);wb[a]={pointerType:f,Y:v};Vb(y,
b);return[c,f,v]})},__embind_register_class_constructor:function(a,b,c,d,f,g){var h=$b(b,c);f=V(d,f);R([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.b.v&&(a.b.v=[]);if(void 0!==a.b.v[b-1])throw new hb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.b.v[b-1]=function(){Zb("Cannot construct "+a.name+" due to unbound types",
h)};R([],h,function(d){a.b.v[b-1]=function(){arguments.length!==b-1&&Q(c+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],h=Array(b);h[0]=g;for(var k=1;k<b;++k)h[k]=d[k].toWireType(a,arguments[k-1]);h=f.apply(null,h);ac(a);return d[0].fromWireType(h)};return[]});return[]})},__embind_register_class_function:function(a,b,c,d,f,g,h,k){var m=$b(c,d);b=O(b);g=V(f,g);R([],[a],function(a){function d(){Zb("Cannot call "+f+" due to unbound types",m)}a=a[0];var f=a.name+"."+b;k&&a.b.ia.push(b);
var l=a.b.C,y=l[b];void 0===y||void 0===y.h&&y.className!==a.name&&y.H===c-2?(d.H=c-2,d.className=a.name,l[b]=d):(xb(l,b,f),l[b].h[c-2]=d);R([],m,function(d){d=cc(f,d,a,g,h);void 0===l[b].h?(d.H=c-2,l[b]=d):l[b].h[c-2]=d;return[]});return[]})},__embind_register_emval:function(a,b){b=O(b);S(a,{name:b,fromWireType:function(a){var b=W[a].value;ec(a);return b},toWireType:function(a,b){return Eb(b)},argPackAdvance:8,readValueFromPointer:Gb,o:null})},__embind_register_float:function(a,b,c){c=$a(c);b=O(b);
S(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Cb(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:jc(b,c),o:null})},__embind_register_function:function(a,b,c,d,f,g){var h=$b(b,c);a=O(a);f=V(d,f);yb(a,function(){Zb("Cannot call "+a+" due to unbound types",h)},b-1);R([],h,function(c){c=[c[0],null].concat(c.slice(1));Vb(a,cc(a,c,null,f,g),b-1);return[]})},__embind_register_integer:function(a,
b,c,d,f){function g(a){return a}b=O(b);-1===f&&(f=4294967295);var h=$a(c);if(0===d){var k=32-8*c;g=function(a){return a<<k>>>k}}var m=-1!=b.indexOf("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+Cb(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+Cb(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return m?
c>>>0:c|0},argPackAdvance:8,readValueFromPointer:kc(b,h,0!==d),o:null})},__embind_register_memory_view:function(a,b,c){function d(a){a>>=2;var b=E;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ea:!0})},__embind_register_std_string:function(a,b){b=O(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(a){var b=E[a>>2];if(c){var d=
C[a+4+b],h=0;0!=d&&(h=d,C[a+4+b]=0);var k=a+4;for(d=0;d<=b;++d){var m=a+4+d;if(0==C[m]){k=D(k);if(void 0===l)var l=k;else l+=String.fromCharCode(0),l+=k;k=m+1}}0!=h&&(C[a+4+b]=h)}else{l=Array(b);for(d=0;d<b;++d)l[d]=String.fromCharCode(C[a+4+d]);l=l.join("")}I(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||Q("Cannot pass non-string to std::string");var f=
(c&&d?function(){return va(b)}:function(){return b.length})(),k=A(4+f+1);E[k>>2]=f;if(c&&d)ua(b,C,k+4,f+1);else if(d)for(d=0;d<f;++d){var m=b.charCodeAt(d);255<m&&(I(k),Q("String has UTF-16 code units that do not fit in 8 bits"));C[k+4+d]=m}else for(d=0;d<f;++d)C[k+4+d]=b[d];null!==a&&a.push(I,k);return k},argPackAdvance:8,readValueFromPointer:Gb,o:function(a){I(a)}})},__embind_register_std_wstring:function(a,b,c){c=O(c);if(2===b){var d=function(){return ya};var f=1}else 4===b&&(d=function(){return E},
f=2);S(a,{name:c,fromWireType:function(a){for(var b=d(),c=E[a>>2],g=Array(c),l=a+4>>f,p=0;p<c;++p)g[p]=String.fromCharCode(b[l+p]);I(a);return g.join("")},toWireType:function(a,c){var g=d(),h=c.length,l=A(4+h*b);E[l>>2]=h;for(var p=l+4>>f,v=0;v<h;++v)g[p+v]=c.charCodeAt(v);null!==a&&a.push(I,l);return l},argPackAdvance:8,readValueFromPointer:Gb,o:function(a){I(a)}})},__embind_register_void:function(a,b){b=O(b);S(a,{fa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
__emval_addMethodCaller:rc,__emval_allocateDestructors:function(a){var b=[];x[a>>2]=Eb(b);return b},__emval_call:function(a,b,c,d){a=nc(a);c=mc(b,c);for(var f=Array(b),g=0;g<b;++g){var h=c[g];f[g]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,f);return Eb(a)},__emval_call_void_method:function(a,b,c,d){a=qc[a];b=nc(b);c=pc(c);a(b,c,null,d)},__emval_decref:ec,__emval_get_method_caller:function(a,b){b=mc(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(a){return a.name}).join("_")+
"$",f=["retType"],g=[c],h="",k=0;k<a-1;++k)h+=(0!==k?", ":"")+"arg"+k,f.push("argType"+k),g.push(b[1+k]);d="return function "+eb("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(k=0;k<a-1;++k)d+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[k+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(d+="    argType"+k+".deleteObject(arg"+k+");\n");c.fa||(d+="    return retType.toWireType(destructors, rv);\n");
f.push(d+"};\n");a=bc(Function,f).apply(null,g);return rc(a)},__emval_incref:function(a){4<a&&(W[a].s+=1)},__emval_lookupTypes:mc,__emval_new_array:function(){return Eb([])},__emval_register:Eb,__emval_take_value:function(a,b){a=lc(a,"_emval_take_value");a=a.readValueFromPointer(b);return Eb(a)},__isLeapYear:Dc,_abort:function(){e.abort()},_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&tc())a=sc();else return Xa(22),-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},_embind_repr:Cb,
_emscripten_get_heap_size:function(){return z},_emscripten_get_now:sc,_emscripten_get_now_is_monotonic:tc,_emscripten_memcpy_big:function(a,b,c){C.set(C.subarray(b,b+c),a)},_emscripten_resize_heap:ma,_getenv:vc,_llvm_stackrestore:function(a){var b=wc.m[a];wc.m.splice(a,1);Y(b)},_llvm_stacksave:wc,_localtime:function(a){return Cc(a,32976)},_localtime_r:Cc,_pthread_cond_wait:function(){return 0},_strftime:Ic,_strftime_l:function(a,b,c,d){return Ic(a,b,c,d)},_tzset:xc,abortOnCannotGrowMemory:function(){t("OOM")},
constNoSmartPtrRawPointerToWireType:Bb,count_emval_handles:fc,craftInvokerFunction:cc,createNamedFunction:fb,downcastPointer:Kb,embind__requireFunction:V,embind_init_charCodes:ab,emscripten_realloc_buffer:uc,ensureOverloadTable:xb,exposePublicSymbol:yb,extendError:gb,floatReadValueFromPointer:jc,flushPendingDeletes:tb,flush_NO_FILESYSTEM:function(){var a=e._fflush;a&&a(0);Ya[1].length&&Za(1,10);Ya[2].length&&Za(2,10)},genericPointerToWireType:Db,getBasestPointer:Qb,getInheritedInstance:Rb,getInheritedInstanceCount:Lb,
getLiveInheritedInstances:Nb,getShiftFromSize:$a,getStringOrSymbol:pc,getTypeName:Xb,get_first_emval:hc,heap32VectorToArray:$b,init_ClassHandle:vb,init_RegisteredPointer:Ub,init_embind:Pb,init_emval:ic,integerReadValueFromPointer:kc,makeClassHandle:Sb,makeLegalFunctionName:eb,new_:bc,nonConstNoSmartPtrRawPointerToWireType:Fb,readLatin1String:O,registerType:S,replacePublicSymbol:Vb,requireHandle:nc,requireRegisteredType:lc,runDestructor:ob,runDestructors:ac,setDelayFunction:Ob,shallowCopyInternalPointer:lb,
simpleReadValueFromPointer:Gb,throwBindingError:Q,throwInstanceAlreadyDeleted:mb,throwInternalError:jb,throwUnboundTypeError:Zb,upcastPointer:Ab,whenDependentTypesAreResolved:R,tempDoublePtr:33120,DYNAMICTOP_PTR:la},buffer);e.asm=md;var ld=e.__ZSt18uncaught_exceptionv=function(){return e.asm.__ZSt18uncaught_exceptionv.apply(null,arguments)};e.___cxa_can_catch=function(){return e.asm.___cxa_can_catch.apply(null,arguments)};
e.___cxa_is_pointer_type=function(){return e.asm.___cxa_is_pointer_type.apply(null,arguments)};var Yb=e.___getTypeName=function(){return e.asm.___getTypeName.apply(null,arguments)},zc=e.__get_daylight=function(){return e.asm.__get_daylight.apply(null,arguments)},yc=e.__get_timezone=function(){return e.asm.__get_timezone.apply(null,arguments)},Bc=e.__get_tzname=function(){return e.asm.__get_tzname.apply(null,arguments)};
e._emscripten_replace_memory=function(){return e.asm._emscripten_replace_memory.apply(null,arguments)};var I=e._free=function(){return e.asm._free.apply(null,arguments)};e._llvm_bswap_i32=function(){return e.asm._llvm_bswap_i32.apply(null,arguments)};var A=e._malloc=function(){return e.asm._malloc.apply(null,arguments)};e._memcpy=function(){return e.asm._memcpy.apply(null,arguments)};e._memmove=function(){return e.asm._memmove.apply(null,arguments)};
e._memset=function(){return e.asm._memset.apply(null,arguments)};e._pthread_cond_broadcast=function(){return e.asm._pthread_cond_broadcast.apply(null,arguments)};e._roundf=function(){return e.asm._roundf.apply(null,arguments)};e._sbrk=function(){return e.asm._sbrk.apply(null,arguments)};var Z=e._setThrew=function(){return e.asm._setThrew.apply(null,arguments)};e.establishStackSpace=function(){return e.asm.establishStackSpace.apply(null,arguments)};
var Qa=e.globalCtors=function(){return e.asm.globalCtors.apply(null,arguments)};e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};
var Y=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},X=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)},Jc=e.dynCall_diii=function(){return e.asm.dynCall_diii.apply(null,arguments)},Kc=e.dynCall_fiii=function(){return e.asm.dynCall_fiii.apply(null,arguments)},Lc=e.dynCall_i=function(){return e.asm.dynCall_i.apply(null,arguments)},Oc=e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)},Pc=e.dynCall_iif=function(){return e.asm.dynCall_iif.apply(null,
arguments)},Qc=e.dynCall_iii=function(){return e.asm.dynCall_iii.apply(null,arguments)},Rc=e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)},Sc=e.dynCall_iiiii=function(){return e.asm.dynCall_iiiii.apply(null,arguments)},Tc=e.dynCall_iiiiid=function(){return e.asm.dynCall_iiiiid.apply(null,arguments)},Uc=e.dynCall_iiiiii=function(){return e.asm.dynCall_iiiiii.apply(null,arguments)};e.dynCall_iiiiiid=function(){return e.asm.dynCall_iiiiiid.apply(null,arguments)};
var Vc=e.dynCall_iiiiiii=function(){return e.asm.dynCall_iiiiiii.apply(null,arguments)},Wc=e.dynCall_iiiiiiii=function(){return e.asm.dynCall_iiiiiiii.apply(null,arguments)},Xc=e.dynCall_iiiiiiiii=function(){return e.asm.dynCall_iiiiiiiii.apply(null,arguments)},Yc=e.dynCall_iiiiiiiiiii=function(){return e.asm.dynCall_iiiiiiiiiii.apply(null,arguments)},Zc=e.dynCall_iiiiiiiiiiii=function(){return e.asm.dynCall_iiiiiiiiiiii.apply(null,arguments)},$c=e.dynCall_iiiiiiiiiiiii=function(){return e.asm.dynCall_iiiiiiiiiiiii.apply(null,
arguments)},ad=e.dynCall_iiiiij=function(){return e.asm.dynCall_iiiiij.apply(null,arguments)},bd=e.dynCall_iij=function(){return e.asm.dynCall_iij.apply(null,arguments)},cd=e.dynCall_jiiii=function(){return e.asm.dynCall_jiiii.apply(null,arguments)},dd=e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)},ed=e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)},fd=e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)},gd=e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,
arguments)},hd=e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};e.dynCall_viiiii=function(){return e.asm.dynCall_viiiii.apply(null,arguments)};e.dynCall_viiiiii=function(){return e.asm.dynCall_viiiiii.apply(null,arguments)};
var id=e.dynCall_viiiiiii=function(){return e.asm.dynCall_viiiiiii.apply(null,arguments)},jd=e.dynCall_viiiiiiiiii=function(){return e.asm.dynCall_viiiiiiiiii.apply(null,arguments)},kd=e.dynCall_viiiiiiiiiiiiiii=function(){return e.asm.dynCall_viiiiiiiiiiiiiii.apply(null,arguments)};e.dynCall_viijii=function(){return e.asm.dynCall_viijii.apply(null,arguments)};e.asm=md;e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};
function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ha.prototype=Error();ha.prototype.constructor=ha;Ka=function nd(){e.calledRun||od();e.calledRun||(Ka=nd)};
function od(){function a(){if(!e.calledRun&&(e.calledRun=!0,!qa)){Ha||(Ha=!0,Ca(Ea));Ca(Fa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Ga.unshift(a)}Ca(Ga)}}if(!(0<F)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ia();Ca(Da);0<F||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=od;function t(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ia(a),u(a),a=JSON.stringify(a)):a="";qa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=t;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;od();


  return VoyMod
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = VoyMod;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return VoyMod; });
    else if (typeof exports === 'object')
      exports["VoyMod"] = VoyMod;
    