import { ContinuumMission } from "../model/continuum";
import { Achiever, CapAchievers, CrewMember, CurrentWeighting, QuipmentScores } from "../model/crew";
import { EquipmentItem } from "../model/equipment";
import { EventInstance, EventLeaderboard, EventScoreSet } from "../model/events";
import { Collection, KeystoneBase, Polestar, Constellation, PortalLogEntry } from "../model/game-elements";
import { Gauntlet } from "../model/gauntlets";
import { Mission } from "../model/missions";
import { ObjectiveEvent } from "../model/player";
import { BattleStations, ReferenceShip, Schematics, Ship } from "../model/ship";
import { StaticFaction } from "../model/shuttle";
import { Dilemma } from "../model/voyage";
import { EventStats } from "../utils/event_stats";
import { BuffStatTable } from "../utils/voyageutils";

export interface ICoreData {
	all_buffs: BuffStatTable;
	all_ships: ReferenceShip[];
	battle_stations: BattleStations[];
	cadet: Mission[];
	collections: Collection[];
	continuum_missions: ContinuumMission[];
	crew: CrewMember[];
	current_weighting: CurrentWeighting;
	dilemmas: Dilemma[];
	episodes: Mission[];
	event_instances: EventInstance[];
	event_leaderboards: EventLeaderboard[];
	event_scoring: EventScoreSet;
	event_stats: EventStats[];
	factions: StaticFaction[];
	ftm_log: Achiever[];
	gauntlets: Gauntlet[];
	items: EquipmentItem[];
	keystones: (KeystoneBase | Polestar | Constellation)[];
	maincast: { [key:string]: string[] };
	missions: Mission[];
	missionsfull: Mission[];
	objective_events: ObjectiveEvent[];
	portal_log: PortalLogEntry[];
	ship_schematics: Schematics[];
	ships: Ship[];
	topQuipmentScores: QuipmentScores[];
};
